### ISSUE TITLE
Hard Coded Specification - Mandatory Tour Scheduling

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#273]
The specifications for mandatory tour scheduling are hard-coded forcing the school and university specification to use the same specification file. In the Atlanta implementation, school and university use different specifications.

https://github.com/ActivitySim/activitysim/blob/7b57c94e12d27a23f86c8988117e885ae754c44e/activitysim/abm/models/mandatory_scheduling.py#L77-L83

It would nice if the model treated the spec more flexibly similar to the way the the location models define the spec. 

https://github.com/ActivitySim/activitysim/blob/7b57c94e12d27a23f86c8988117e885ae754c44e/activitysim/abm/models/location_choice.py#L251

I could imagine a situation where the mandatory specs are defined in the mandatory_tour_scheduling.yaml as follow:

```
SPEC:
  work: tour_scheduling_work.csv
  school: tour_scheduling_school.csv
  univ: tour_scheduling_university.csv
```
